version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Iniciando la compilación y pruebas del servidor"
      - npm install  # Instalar las dependencias del servidor
      - npm run build  # Compilar el servidor (si es necesario, dependiendo de tu aplicación)