org: nelsoncastellanos
app: porvenirecommerce
service: porvenirEcommerce

provider:
  name: aws
  ecr:
    images:
      porvenir_ecommerce:
        path: ./

functions:
  porvenirEcommerce:
    image:
      name: porvenir_ecommerce
    events:
      - httpApi:
          path: /
          method: ANY
    environment:
      PORT: 3000
      MONGO_URI: ${secrets:porvenir_monogodb_uri}
      JWT_SECRET: ${secrets:porvenir_jwt_secret}
      MAILCHIMP_KEY:
      MAILCHIMP_LIST_KEY:
      MAILGUN_KEY:
      MAILGUN_DOMAIN:
      MAILGUN_EMAIL_SENDER:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      GOOGLE_CALLBACK_URL: auth/google/callback
      FACEBOOK_CLIENT_ID:
      FACEBOOK_CLIENT_SECRET:
      FACEBOOK_CALLBACK_URL: auth/fECSacebook/callback
      BASE_CLIENT_URL: ${param:porvenir_client_url}
      BASE_SERVER_URL: ${param:porvenir_server_url}
      BASE_API_URL: api
      AWS_ACCESS_KEY_ID: ${secrets:porvenir_aws_access_key_id}
      AWS_SECRET_ACCESS_KEY: ${secrets:porvenir_aws_secret_access_key}
      AWS_REGION: ${param:porvenir_aws_region}
      AWS_BUCKET_NAME: elporvenir-ecommerce-content